version: '3.3'

services:
  traefik:
    image: traefik:v2.4
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=web
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --entrypoints.web.address=:${HTTP_PORT}
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:${HTTPS_PORT}
      - --entrypoints.websecure.http.middlewares=default@file
      - --entrypoints.websecure.http.tls.domains=${DEFAULT_DOMAIN}
      - --entrypoints.websecure.http.tls.options=default@file
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      # Enable API
      #- --api
      # Optionally uncomment the following lines if you want to test/debug:
      #- --log.level=DEBUG
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - 80:80
      - 443:443
      # Enable API
      #- 8080:8080
    networks:
      - web
    volumes:
      - ./config:/etc/traefik:ro
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: traefik

networks:
  web:
    external: true

volumes:
  letsencrypt:
