name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check-docker-compose-syntax:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Docker Compose file syntax
        run: docker compose --env-file .env.dist config -q
  check-markdown-syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint Markdown
      uses: articulate/actions-markdownlint@v1
      with:
        files: '**/*.md'